project:
  type: website

website:
  title: "Home"
  navbar:
    left:
      - text: "Home"
        href: index.qmd
      - text: "Projects"
        menu:
          - text: "CNN Model"
            href: projects/cnn_model.qmd
          - text: "Survival Analysis and Life Table"
            href: projects/survival_analysis.qmd
          - text: "Time Series Analysis"
            href: projects/time_series.qmd
      - text: "About Me"
        menu:
          - text: "Goals"
            href: about_me/goals.qmd
          - text: "Education"
            href: about_me/education.qmd

format:
  html:
    theme: flatly
    css: styles.css
    embed-resources: true

