name: Render and Deploy Quarto Site

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      # 1) Define a writable R library path and persist it to all steps
      - name: Set up R library path
        run: |
          echo "R_LIBS_USER=${RUNNER_TEMP}/R/library" >> $GITHUB_ENV
          mkdir -p "${RUNNER_TEMP}/R/library"

      # 2) Install R itself
      - name: Setup R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: "4.2"

      # 3) Install needed R packages into that library
      - name: Install required R packages
        run: |
          Rscript -e 'install.packages(
            c("knitr","rmarkdown","reticulate"),
            repos="https://cloud.r-project.org"
          )'

      # 4) Install Quarto CLI
      - name: Setup Quarto
        uses: quarto-dev/quarto-actions/setup@v2

      # 5) Render the site (fresh, no cache)
      - name: Render site
        run: quarto render --no-cache

      # 6) Push built files to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs
          publish_branch: gh-pages
