name: Deploy Quarto Website

on:
  push:
    branches:
      - main  # Runs the workflow whenever you push to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Setup Quarto
        uses: quarto-dev/quarto-actions/setup@v2
        with:
          version: latest

      # Step 3: Render the Quarto site
      - name: Render Quarto site
        run: quarto render

      # Step 4: Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_site  # Deploy the '_site/' folder
